using System;
namespace AppInterfaces
{
    public class PasswordManager : IDisplayable
    {
        //FIELD(s)
        //auto-generated by compiler with the auto-implemented properties


        //PROPERTIE(s)
        private string Password
        { get; set; }

        public bool Hidden
        { get; private set; }



        //CONSTRUCTOR(s)
        //no parameterless constructor available!
        public PasswordManager(string password, bool hidden)
        {
            Password = password;
            Hidden = hidden;
        }


        //METHOD(s)
        public void Display()
        {
            if (Hidden)
            {
                Console.WriteLine("Password: ***");
            }
            else
            {
                Console.WriteLine($"Password: {Password}");
            }
        }
    }
}
